### ISSUE TITLE
Blank screen/unresponsive when used on Nginx server

### ISSUE THREAD

**Issue by charlesfries** [LazarSoft/jsqrcode#44]

**Comment by Danish22** [comment]
You found the solution? Am facing the same issue.

**Comment by zinthose** [comment]
I figured out that you need to run the page with an SSL cert (https).  This is due to Chrome security settings preventing the getUserMedia APIs from being accessible from an unencrypted page.

**Comment by Danish22** [comment]
Yes, all the browser require SSL certificate to access you webcam.
