### ISSUE TITLE
Please add license to npm package

### ISSUE THREAD

**Issue by mkotsbak** [LazarSoft/jsqrcode#46]
I tried to import the NPM package into a Webjar, but it fails because the package has no license registered.

**Comment by shielamp13** [comment]
<p xmlns:dct="http://purl.org/dc/terms/">
<a rel="license" href="http://creativecommons.org/publicdomain/mark/1.0/">
<img src="http://i.creativecommons.org/p/mark/1.0/88x31.png"
     style="border-style: none;" alt="Public Domain Mark" />
</a>
<br />
This work (<span property="dct:title">Lovell Landscaping</span>, by <a href="lovelllandscaping.com" rel="dct:creator"><span property="dct:title">Shiela M. Parker</span></a>), identified by <a href="lovelllandscaping.com" rel="dct:publisher"><span property="dct:title">Shiela M. Parker</span></a>, is free of known copyright restrictions.
</p>

**Comment by mkotsbak** [comment]
Ok, thanks. I think someone else uploaded it to Npm. Anyway the npm package zxing is now available in Webjars.
