### ISSUE TITLE
change camera (front/wear)

### ISSUE THREAD

**Issue by matheuseduardo** [LazarSoft/jsqrcode#48]
Is there a way to change camera used to scan?

When I opened on my phone, open the front camera, instead the rear camera.

**Comment by ondrejpolach** [comment]
Use MediaStreamTrack.getSources(callback) for getting autio/video sources. Each source has id. This id use in navigator.getUserMedia({audio: false, video: {optional: [{sourceId: id}]}}, success, error)

**Comment by matheuseduardo** [comment]
I can't explain all the code right now.. but I used constraints, like: 

```
	var constraints = {
		video: {	
			deviceId: videoSource ? {exact: videoSource} : undefined,
			facingMode: "environment"
		}
	};
```

and then:
`navigator.mediaDevices.getUserMedia(constraints).then(gotStream).then(gotDevices).catch(handleError);`

good luck, if someone need it.

**Comment by matheuseduardo** [comment]
I had to use https://github.com/webrtc/adapter to make everything work great. :)
