### ISSUE TITLE
[feature request] moving / multi-frame qr codes

### ISSUE THREAD

**Issue by mvayngrib** [LazarSoft/jsqrcode#50]
https://www.youtube.com/watch?v=y0n2nXBbL_Q

how hard would it be to support scanning + stiching together the codes from a looping gif?

(also opened here https://github.com/defunctzombie/qr.js/issues/2)

**Comment by maxg0** [comment]
I have actually made a javascript library called [DisplaySocket.js](https://github.com/maxg0/displaysocket.js) that does this, even though it doesn't specifically use gifs. I also host a demo [on my website](http://max.grasbeck.com/displaysocket.js/).

**Comment by mvayngrib** [comment]
@maxg0 that's looks great! I wasn't able to get the demo on your website working because of certificates, but i cloned and tried in on my localhost. Chrome complains about MediaStream.getSources being deprecated, but once i got rid of that, it seemed to work

**Comment by maxg0** [comment]
It should be asking for permissions when it's not over https but it's been about a year since I tested that things worked so some problems are to be expected. I'd love a pull request if you get it to work properly
