### ISSUE TITLE
can't decode multiple times

### ISSUE THREAD

**Issue by dwikiriyadi** [LazarSoft/jsqrcode#68]
i try to use jsqrcode on electron application with stream decode, but it just scan only one time, when i start the webcam again it say "qrcode.decode is not a function", i want to know how to use it for multiple times

**Comment by mwj-1992** [comment]
you only need to call setwebcam() function  after scan success.... i faced same issue and fix it by calling this function after scanning ..

**Comment by iShubhamRaj** [comment]
Hi @mwj-1992 How to know when it has successfully scanned one time? I can't figure out which event it fires or how to hook into a successful scan. Please help out here.

**Comment by ayubUOL** [comment]
Use setInterval to get canvas and pass it to decode function then you can achieve decode multiple times.
