### ISSUE TITLE
Issue with mobile devices

### ISSUE THREAD

**Issue by missing** [LazarSoft/jsqrcode#9]
Chrome for Android allows getUserMedia behind a flag now. Sadly the decoder seems to struggle on any mobile devices. Testing on webqr.com with a version 1 QR code on desktop and using getUserMedia is amazingly fast. However on a chrome tablet (tested on Nexus 7 & Asus Transformer) with version 1 QR you'll get an error: "Error getVersionForNumber". Then I tested version 3 QR code as well, and it will make it past the version check and then fail on: "ReedSolomonException Bad error location". And finally on version 4 QR code you'll get this error: "Error locator degree does not match number of roots"

Any ideas why this would be happening on mobile only?

**Comment by rubensfernandes** [comment]
GOOD NEWS 

solved the issue,

just add the following line in your qrscanner.js

video.setAttribute('autoplay','');

https://github.com/sembrestels/angular-qr-scanner/issues/5

**Comment by cfmonk** [comment]
Dragging up an old issue but I'm still trying to implement this on Android. It needs to work on both iOs and Android. I did the Vertical Stretch fix for iOs but Android will not work with an upload from the camera. It works with a saved photo (taken on the same device) but not an upload. I'm tearing my hair out!

**Comment by gansky-alexander** [comment]
Hello, guys ! Do you have any solution ?
